/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WallpapersRouteImport } from './routes/wallpapers'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as RunRouteImport } from './routes/run'
import { Route as RelationshipsRouteImport } from './routes/relationships'
import { Route as HanpaopaoRouteImport } from './routes/hanpaopao'
import { Route as GameRouteImport } from './routes/game'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as IndexRouteImport } from './routes/index'

const WallpapersRoute = WallpapersRouteImport.update({
  id: '/wallpapers',
  path: '/wallpapers',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const RunRoute = RunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipsRoute = RelationshipsRouteImport.update({
  id: '/relationships',
  path: '/relationships',
  getParentRoute: () => rootRouteImport,
} as any)
const HanpaopaoRoute = HanpaopaoRouteImport.update({
  id: '/hanpaopao',
  path: '/hanpaopao',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/game': typeof GameRoute
  '/hanpaopao': typeof HanpaopaoRoute
  '/relationships': typeof RelationshipsRoute
  '/run': typeof RunRoute
  '/timeline': typeof TimelineRoute
  '/wallpapers': typeof WallpapersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/game': typeof GameRoute
  '/hanpaopao': typeof HanpaopaoRoute
  '/relationships': typeof RelationshipsRoute
  '/run': typeof RunRoute
  '/timeline': typeof TimelineRoute
  '/wallpapers': typeof WallpapersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/game': typeof GameRoute
  '/hanpaopao': typeof HanpaopaoRoute
  '/relationships': typeof RelationshipsRoute
  '/run': typeof RunRoute
  '/timeline': typeof TimelineRoute
  '/wallpapers': typeof WallpapersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artifacts'
    | '/game'
    | '/hanpaopao'
    | '/relationships'
    | '/run'
    | '/timeline'
    | '/wallpapers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artifacts'
    | '/game'
    | '/hanpaopao'
    | '/relationships'
    | '/run'
    | '/timeline'
    | '/wallpapers'
  id:
    | '__root__'
    | '/'
    | '/artifacts'
    | '/game'
    | '/hanpaopao'
    | '/relationships'
    | '/run'
    | '/timeline'
    | '/wallpapers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtifactsRoute: typeof ArtifactsRoute
  GameRoute: typeof GameRoute
  HanpaopaoRoute: typeof HanpaopaoRoute
  RelationshipsRoute: typeof RelationshipsRoute
  RunRoute: typeof RunRoute
  TimelineRoute: typeof TimelineRoute
  WallpapersRoute: typeof WallpapersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallpapers': {
      id: '/wallpapers'
      path: '/wallpapers'
      fullPath: '/wallpapers'
      preLoaderRoute: typeof WallpapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run': {
      id: '/run'
      path: '/run'
      fullPath: '/run'
      preLoaderRoute: typeof RunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationships': {
      id: '/relationships'
      path: '/relationships'
      fullPath: '/relationships'
      preLoaderRoute: typeof RelationshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hanpaopao': {
      id: '/hanpaopao'
      path: '/hanpaopao'
      fullPath: '/hanpaopao'
      preLoaderRoute: typeof HanpaopaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtifactsRoute: ArtifactsRoute,
  GameRoute: GameRoute,
  HanpaopaoRoute: HanpaopaoRoute,
  RelationshipsRoute: RelationshipsRoute,
  RunRoute: RunRoute,
  TimelineRoute: TimelineRoute,
  WallpapersRoute: WallpapersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
